// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {prismaTokens} from "./tokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: ".^QVQROOOnQRO'#CjOsQRO'#C|OxQRO'#C}OOQP'#DS'#DSQVQROOO}QQO,59UO!SQQO,59hO!XQRO,59iOOQP-E7Q-E7QO!aQRO1G.pO!oQRO1G/SO!zQRO1G/TO#VQQO1G/TO#[QRO'#ClO#aQRO'#CzOOQP'#DT'#DTO#rQRO7+$[OOQP7+$[7+$[OOQP'#DX'#DXO$QQRO7+$nOOQP7+$n7+$nO$]QQO'#DOOOQP'#DY'#DYO$bQRO7+$oOOQP7+$o7+$oO$bQRO7+$oO$mQRO'#CmO%[QRO,59WO&OQRO,59fOOQP-E7R-E7ROOQP<<Gv<<GvOOQP-E7V-E7VOOQP<<HY<<HYO&VQRO,59jOOQP-E7W-E7WOOQP<<HZ<<HZO&eQRO<<HZOOQP,59X,59XO&pQRO,59XO'XQRO,59XO'^QRO'#CrOOQP'#DU'#DUO'rQRO1G.rO(TQQO'#CsOOQO'#Cs'#CsO(`QQO'#CsO(eQRO'#CsOOQP1G/Q1G/QO(jQQO1G/QO(rQQO'#CtOOQP'#DQ'#DQO(wQRO'#DQOOQP1G/U1G/UOOQPAN=uAN=uOOQP1G.s1G.sO)SQQO1G.sO)XQRO,59^OOQP-E7S-E7SO)`QRO,59`O)gQRO,59_OOQO'#Cw'#CwO)oQQO,59_O%mQRO'#DVO)wQQO7+$lOOQP7+$l7+$lOOQO'#DR'#DRO*PQQO,59lO*XQRO7+$_OOQP1G.x1G.xO*sQQO1G.xOOQP1G.z1G.zO*{QQO1G.zOOQO1G.y1G.yO(eQRO1G.yO(eQRO'#DWO+TQQO1G.yOOQO,59q,59qOOQO-E7T-E7TOOQP<<HW<<HWO(wQRO'#DZO+]QQO1G/WOOQP1G/W1G/WOOQP<<Gy<<GyO+eQRO<<GyO+|QQO7+$dOOQP7+$d7+$dO,UQQO7+$fOOQP7+$f7+$fO,^QQO7+$eOOQO,59r,59rOOQO-E7U-E7UOOQO7+$e7+$eOOQO,59u,59uOOQO-E7X-E7XOOQP7+$r7+$rOOQPAN=eAN=eOOQP<<HO<<HOOOQP<<HQ<<HQO,fQQO<<HPOOQO<<HP<<HPOOQOAN=kAN=k",
  stateData: ",n~O!QOS~OPSO!RPO!SPO!TPO!UQO!VRO!WRO~OQUO~OQVO~OQWO~O_YO~O_ZO~OW]O_[O~OP`OR^OV_OobO~OPcOTcOoeO~OPgORfOoiO~O_jO~OSkO~ObmOPnXRnXVnXonX~OP`OR^OV_OooO~OPcOTcOoqO~OsrO~OPgORfOotO~OYwObxOdvOevOPaXRaXUaXVaXoaX~OUyOP`aR`aV`ao`a~OQ|OW}OX}OZ!OOl!PO~Oc!QO~P%mOQ!SOW!TOX!TOl!UO~OPgORfOo!WO~Od!XOe!XOPaaRaaUaaVaaoaa~OW!YO~Ob!ZOPfXRfXUfXVfXofX~OUyOP`iR`iV`io`i~Ob!]OcgXigX~Oj!^O~O[!_O~Oc!cOi!aO~Ob!]O~OQ!dOW!dOX!dO~Oc!fO~Oc!gO~P%mOc!iO~P%mO[!_Ol!lO~Oi!mOm!kO~Oc!qOi!aO~Oi!rOm!tO~OY!vOd!uOe!uOPaqRaqUaqVaqoaq~Oc!xOi!aO~Oc!zOi!aO~Oi!mOm#OO~Oi!rOm#RO~Od#SOe#SOPayRayUayVayoay~Oc#TOi!aO~Oc#UOi!aO~Oi!mOm#WO~Oi!mOm#XO~O",
  goto: "$t!OPPPPPPPPPPPPPP!PP!T!XPPPP![!`!lPP!uPP!TP!P!P#RP#X#[#b#h#n#t$S$^$d$nTSOTT`YaRl^Tzl{Q!RmQ!h!ZQ!j!]R!o!aW}m!Z!]!aR!TrQ!`!PQ!k!^Q!{!lR!|!mXg[hjuR!VrQ!e!UR#P!rQTORXTQaYRnaQ{lR![{Q!b!RU!p!b!w!yQ!w!hR!y!jQ!n!`S!}!n#VR#V!{QdZRpdQh[SshuRujQ!s!eR#Q!s",
  nodeNames: "⚠ LineComment Identifier FieldName Type EnumValue AttributeName BlockAttrName String Number ArrayMarker AttrKey AttrValue Program ModelBlock { ModelField FieldType ( ) ? ! Attribute FunctionArg FunctionCall , : AttrArgValue [ ] BlockAttribute } EnumBlock ConfigBlock Assignment = FieldValue ConfigArrayValue",
  maxTerm: 54,
  skippedNodes: [0],
  repeatNodeCount: 8,
  tokenData: "(j~ReXY!dYZ!d]^!dpq!dqr!uxy!zyz#P|}#U![!]#Z!_!`#`!a!b#e!}#O#j#P#Q#o#W#X#t#X#Y%R#Z#[%j#a#b&q#h#i'`#j#k'w#o#p(`#q#r(e~!iS!Q~XY!dYZ!d]^!dpq!d~!zOe~~#POb~~#UOc~~#ZOi~~#`Oj~~#eOs~~#jOd~~#oOl~~#tOm~~#wP#T#U#z~#}P#h#i$Q~$TP#T#U$W~$ZP#g#h$^~$aP#c#d$d~$gP#i#j$j~$mP#f#g$p~$sP#V#W$v~$yP#X#Y$|~%RO!V~~%UP#b#c%X~%[P#i#j%_~%bP#a#b%e~%jO!U~~%mP#X#Y%p~%sP#b#c%v~%yP#X#Y%|~&PP#f#g&S~&VP#T#U&Y~&]P#h#i&`~&cP#c#d&f~&iP#f#g&l~&qO!W~~&tP#c#d&w~&zP#W#X&}~'QP#X#Y'T~'WP#`#a'Z~'`O!R~~'cP#m#n'f~'iP#d#e'l~'oP#X#Y'r~'wO!S~~'zP#]#^'}~(QP#X#Y(T~(WP#k#l(Z~(`O!T~~(eO_~~(jOo~",
  tokenizers: [prismaTokens, 0],
  topRules: {"Program":[0,13]},
  dialects: {multi: 0},
  tokenPrec: 0
})
